### PR TITLE
Redirect to InstantCena

### PR DESCRIPTION
**Pull request by xavdid**
Also, simplified code because of that change

### CODE REVIEW

**Comment by Roystbeef** [comment]
hmm, idk how i feel about the redirect. What are your thoughts on injecting the mp4 and webm from instantcena @Xavdidtheshadow? The pros of the latter makes it redirect to their original page after it plays.

**Comment by xavdid** [comment]
@Roystbeef I think I like the redirect more because no one is going to (voluntarily) let it play all the way out anyway, so with the redirect they can chuckle and then just navigate back to their original page. Plus, if anything changes at instantcena, your code won't break if they change the filename or anything. Plus, you benefit from any changes they make!

**Comment by xavdid** [comment]
unrelated, I just noticed that I misinterpreted your timeout- right now if mine triggers, it waits 20 seconds, then redirects. That's silly. 

I'd change it to one of two things:
1. Wait 3-5 seconds, so it seems like nothing is happening, then redirect
2. Remove the timeout and just send them right through to the next page if it triggers.

Trying them locally, I kind of like #1

**Comment by xavdid** [comment]
I just updated it accordingly. I then forgot to disable it and just got myself, so there's that. I like the 3 second wait a lot, haha.

**Comment by Roystbeef** [comment]
Sorry for the late reply! Yeah, so I set the timeout for 20 seconds bc that's how long the soundclip is, but having a different one that's called before it loads john cena is genius. In regards to using the mp4/webm, I was probably going to download them and then reference them in the same way I am currently with the gif and soundclip.

**Comment by xavdid** [comment]
nice. I'll close the PR

**Pull request closed without merging**
